[theme]
primaryColor = "#0E7C7B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F9FB"
textColor = "#0F2038"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
